server
{
	# Listens on port 443 for SSL connections
	listen 443 ssl;
	# Server name
	server_name localhost;


	# SSL configuration with certificate and key paths
	ssl_certificate /etc/nginx/ssl/inception.crt;
	ssl_certificate_key /etc/nginx/ssl/inception.key;
	ssl_protocols TLSv1.2 TLSv1.3;


	# Root directory for wordpress
	root /var/www/html;
	# Default index files, it's the entrypoint to the website
	index index.php index.html;


	# Tries the url path and sends it to index if it doesn't exist
	location /
	{
		try_files $uri $uri/ /index.php?$args;
	}

	# Tries the url path and sends it to the wordpress container if it ends with .php
	location ~ \.php$
	{
		include fastcgi_params;
		fastcgi_pass wordpress:9000;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}


	# If location / doesn't have a .php ending it sends the index to location ~ \.php$
}
